### ISSUE TITLE
iOS 无法加载IOKit.framework，加载失败；使用系统的dlopen可以

### ISSUE THREAD

**Issue by Antinust** [hack0z/byOpen#10]
### 描述问题
void *IOKit = by_dlopen("/System/Library/Frameworks/IOKit.framework/IOKit", BY_RTLD_NOW);
运行👆那行代码后，得到的IOKit为空

### 期待的结果
期望得到非空的handle

### 相关环境
xcode 13.4.1
iOS 15.5

**Comment by waruqi** [comment]
去掉路径试下，或者自己调下 https://github.com/hack0z/byopen/blob/ddd9c2d66e5383fdcc266290d5822fff1dd21e6d/src/native/byopen_macho.c#L95

**Comment by Antinust** [comment]
> void *IOKit = by_dlopen("/System/Library/Frameworks/IOKit.framework/IOKit", BY_RTLD_NOW);

路径改成/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit就可以了，(通过打印所有的库，发现IOKit传入的路径与系统的不匹配)，代码如下：
`void *IOKit = by_dlopen("/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit", BY_RTLD_NOW);`
