### ISSUE TITLE
请求更新某些设备上存在的bug

### ISSUE THREAD

**Issue by liuyou** [hack0z/byOpen#3]
In function ·by_fake_find_maps·
byopen calls sscanf to get loaded so's base address and offset
but it does not check if the mmap memory is executable,so sometimes byopen will return error handle.

fix it by check whether the page flags has "x"

**Comment by waruqi** [comment]
最近没啥时间看这个，你可以提个pr过来帮忙改下。

**Comment by liuyou** [comment]
提了，不是很优雅，因为在我的一台老的安卓设备上不知道为什么不能用%c%cx%c进行过滤，所以直接先把属性提出来再判断了

**Comment by waruqi** [comment]
过滤 x 也不行，很多设备 maps 上 一个 so 过滤了 x 后的，offset 都不是 0，算出来的 baseaddr 还是不对，尤其是 11 上会取错。

**Comment by liuyou** [comment]
我本地更新了一个版本，减去offset就可以了
没提pr。。
![image](https://user-images.githubusercontent.com/3992446/117269047-854bf680-ae8a-11eb-8f79-802a9c75bde5.png)

**Comment by liuyou** [comment]
我没用 11设备测试过，我在10的设备上 读取linker的符号的时候遇到这个问题了
![image](https://user-images.githubusercontent.com/3992446/117269250-b4626800-ae8a-11eb-8f5c-658a0dc14590.png)

你直接改一下咯，哈哈哈

**Comment by liuyou** [comment]
> 过滤 x 也不行，很多设备 maps 上 一个 so 过滤了 x 后的，offset 都不是 0，算出来的 baseaddr 还是不对，尤其是 11 上会取错。

我这段时间比较忙，后面有时间了打算直接对linker打补丁

**Comment by waruqi** [comment]
> 我本地更新了一个版本，减去offset就可以了
> 没提pr。。
> ![image](https://user-images.githubusercontent.com/3992446/117269047-854bf680-ae8a-11eb-8f79-802a9c75bde5.png)

我现在 master 的就是减了 offset 的。。android 11/armv7 上必崩，内部调用 android_runtime.so getenv 时候，就是 so baseaddr  在 减去 offset 后算出来的 baseaddr 值，跟首行 offset 的那个 baseaddr 后有偏差

减去 offset 算的不是完全准的。

**Comment by waruqi** [comment]
> 我没用 11设备测试过，我在10的设备上 读取linker的符号的时候遇到这个问题了
> ![image](https://user-images.githubusercontent.com/3992446/117269250-b4626800-ae8a-11eb-8f5c-658a0dc14590.png)
> 
> 你直接改一下咯，哈哈哈

你这个是老版本的，master 上老早减掉 offset 了。。不过也不完全对

**Comment by liuyou** [comment]
> > 我本地更新了一个版本，减去offset就可以了
> > 没提pr。。
> > ![image](https://user-images.githubusercontent.com/3992446/117269047-854bf680-ae8a-11eb-8f79-802a9c75bde5.png)
> 
> 我现在 master 的就是减了 offset 的。。android 11/armv7 上必崩，内部调用 android_runtime.so getenv 时候，就是 so baseaddr 在 减去 offset 后算出来的 baseaddr 值，跟首行 offset 的那个 baseaddr 后有偏差
> 
> 减去 offset 算的不是完全准的。

拉到ida里看下，差多少？我晚点找个 11看看，是计算 libandroid_runtime.so的函数有偏差吗？32位还是 64位？
